"""Tests for the shared review service, including the structured review parser."""

from __future__ import annotations

from gh_pr_reviewer import service

FULL_REVIEW = """## Decision
- Status: `Needs changes`
- Risk: `High`
- Main reason: The migration drops rows without a backup.

## Findings

### [P0] Migration deletes rows with no backup
- File: `db/migrations/004_drop.sql`
- Evidence: The new migration runs `DELETE FROM orders` before the copy step.
- Impact: Production order history is lost on deploy.
- Fix: Copy into `orders_archive` first, then delete.

### [P2] Retry counter is never reset
- File: `app/worker.py:88`
- Evidence: `attempts` stays at its last value between jobs.
- Impact: Later jobs give up early.
- Fix: Reset the counter at the start of each job.

## Summary
The migration is unsafe as written. The retry bug is smaller but real.
"""


def test_parse_review_extracts_decision():
    parsed = service.parse_review_markdown(FULL_REVIEW)
    assert parsed is not None
    assert parsed["decision"] == {
        "status": "Needs changes",
        "risk": "High",
        "main_reason": "The migration drops rows without a backup.",
    }


def test_parse_review_extracts_findings():
    parsed = service.parse_review_markdown(FULL_REVIEW)
    assert len(parsed["findings"]) == 2

    first = parsed["findings"][0]
    assert first["priority"] == "P0"
    assert first["title"] == "Migration deletes rows with no backup"
    assert first["file"] == "db/migrations/004_drop.sql"
    assert first["line"] is None
    assert first["evidence"].startswith("The new migration")
    assert first["impact"].startswith("Production order history")
    assert first["fix"].startswith("Copy into")

    second = parsed["findings"][1]
    assert second["priority"] == "P2"
    assert second["file"] == "app/worker.py"
    assert second["line"] == 88


def test_parse_review_extracts_summary():
    parsed = service.parse_review_markdown(FULL_REVIEW)
    assert parsed["summary"].startswith("The migration is unsafe")


def test_parse_review_handles_no_findings():
    text = """## Decision
- Status: `Ready`
- Risk: `Low`
- Main reason: The change is a docs edit.

## Findings
No blocking issues found.

## Summary
Docs only.
"""
    parsed = service.parse_review_markdown(text)
    assert parsed["decision"]["status"] == "Ready"
    assert parsed["findings"] == []
    assert parsed["summary"] == "Docs only."


def test_parse_review_returns_none_for_free_text():
    assert service.parse_review_markdown("I cannot review this.") is None
    assert service.parse_review_markdown("") is None
    assert service.parse_review_markdown("   ") is None


def test_parse_review_survives_a_council_header():
    text = "> **Council Review Consensus**\n> Generated by: `claude`\n\n" + FULL_REVIEW
    parsed = service.parse_review_markdown(text)
    assert parsed["decision"]["status"] == "Needs changes"
    assert len(parsed["findings"]) == 2


def test_parse_review_accepts_bold_field_labels():
    text = """## Decision
- **Status:** Ready
- **Risk:** Low
- **Main reason:** Nothing risky changed.

## Findings

### [P3] Minor naming nit
- **File:** `app/util.py`
- **Evidence:** The helper name no longer matches its behaviour.
- **Impact:** Readers get confused.
- **Fix:** Rename the helper.

## Summary
Small change.
"""
    parsed = service.parse_review_markdown(text)
    assert parsed["decision"]["risk"] == "Low"
    assert parsed["findings"][0]["priority"] == "P3"
    assert parsed["findings"][0]["file"] == "app/util.py"


def test_extract_review_markdown_trims_chatter():
    raw = "Reading files...\nThinking...\n## Decision\n- Status: `Ready`\ntokens used\n1234"
    assert service.extract_review_markdown(raw).startswith("## Decision")
    assert "tokens used" not in service.extract_review_markdown(raw)


def test_looks_like_raw_diff():
    assert service.looks_like_raw_diff("diff --git a/a.py b/a.py\n+x")
    many = "\n".join(["@@ -1 +1 @@"] * 6)
    assert service.looks_like_raw_diff(many)
    assert not service.looks_like_raw_diff("## Findings\n@@ -1 +1 @@")
    assert not service.looks_like_raw_diff("")


def test_summarize_provider_error():
    assert service.summarize_provider_error("claude timed out (5 min)") == "timeout"
    assert service.summarize_provider_error("You have hit your usage limit") == "quota or usage limit"
    assert service.summarize_provider_error("codex CLI not found") == "not found"
    assert service.summarize_provider_error("operation not permitted") == "permission or sandbox issue"


def test_generate_review_single_provider(monkeypatch):
    monkeypatch.setattr(service, "call_ai_cli", lambda p, d, wrap=True: (True, "## Decision\n- Status: `Ready`"))
    result = service.generate_review("diff", "claude")
    assert result["success"] is True
    assert result["participants"] == ["claude"]
    assert result["skipped"] == []


def test_generate_review_single_provider_failure(monkeypatch):
    monkeypatch.setattr(service, "call_ai_cli", lambda p, d, wrap=True: (False, "claude timed out (5 min)."))
    result = service.generate_review("diff", "claude")
    assert result["success"] is False
    assert "timed out" in result["error"]


def test_council_partial_failure(monkeypatch):
    monkeypatch.setattr(service, "get_available_providers", lambda: ["claude", "antigravity", "codex"])

    def fake_cli(provider, text, wrap=True):
        if provider == "antigravity":
            return False, "agy failed: usage limit reached"
        if not wrap:
            return True, "## Decision\n- Status: `Ready`\n\n## Summary\nSynthesized."
        return True, f"## Decision\n- Status: `Ready`\n\n## Summary\nFrom {provider}."

    monkeypatch.setattr(service, "call_ai_cli", fake_cli)
    result = service.generate_review("diff", "council")
    assert result["success"] is True
    assert sorted(result["participants"]) == ["claude", "codex"]
    assert result["moderator"] == "claude"
    assert result["skipped"] == [{"provider": "antigravity", "reason": "quota or usage limit"}]


def test_council_all_providers_fail(monkeypatch):
    monkeypatch.setattr(service, "get_available_providers", lambda: ["claude", "codex"])
    monkeypatch.setattr(service, "call_ai_cli", lambda p, d, wrap=True: (False, f"{p} timed out"))
    result = service.generate_review("diff", "council")
    assert result["success"] is False
    assert "All council reviewers failed" in result["error"]


def test_council_with_no_providers_installed(monkeypatch):
    monkeypatch.setattr(service, "get_available_providers", lambda: [])
    result = service.generate_review("diff", "council")
    assert result["success"] is False
    assert "No supported AI CLIs" in result["error"]


def test_council_with_one_provider_falls_back_to_single_review(monkeypatch):
    monkeypatch.setattr(service, "get_available_providers", lambda: ["codex"])
    monkeypatch.setattr(service, "call_ai_cli", lambda p, d, wrap=True: (True, "## Decision\n- Status: `Ready`"))
    result = service.generate_review("diff", "council")
    assert result["success"] is True
    assert result["participants"] == ["codex"]
    assert "only `codex` was found" in result["review"]


def test_council_synthesis_failure_appends_individual_reviews(monkeypatch):
    monkeypatch.setattr(service, "get_available_providers", lambda: ["claude", "codex"])

    def fake_cli(provider, text, wrap=True):
        if not wrap:
            return False, "claude timed out (5 min)."
        return True, f"## Decision\n- Status: `Ready`\n\n## Summary\nFrom {provider}."

    monkeypatch.setattr(service, "call_ai_cli", fake_cli)
    result = service.generate_review("diff", "council")
    assert result["success"] is True
    assert "Synthesis failed" in result["review"]
    assert result["moderator"] is None


def test_valid_provider_values():
    assert service.VALID_PROVIDER_VALUES == {"claude", "antigravity", "codex", "council"}
